name: Android Build APK

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]
        
    steps:
    - uses: actions/checkout@v2 
    - name: Install latest nightly
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true
        components: rustfmt, clippy

      # `cargo check` command here will use installed `nightly`
      # as it is set as an "override" for current directory

    - name: Run cargo check
      uses: actions-rs/cargo@v1
      with:
        command: check
  
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install -g codecov
    - run: yarn
   
   
    - name: Make Gradlew Executable
      run: cd android && chmod +x ./gradlew
        # Build Command
    - name: Build Android Release
      run: yarn release
      # Upload to Artifact
    - name: Upload Artifact
      uses: actions/upload-artifact@v1
      with:
        name: app-release.apk
        path: android/app/build/outputs/apk/release/
