name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]
        rust:
          - stable
          - beta
          - nightly
    steps:
    - uses: actions/checkout@v2
      
    - uses: actions-rs/toolchain@v1
      with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true
          components: rustfmt, clippy
          
    - name: Run cargo check
      uses: actions-rs/cargo@v1
      with:
        command: check
          
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install -g codecov
    - run: yarn
    - run: yarn test
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
    - name: Make Gradlew Executable
      run: cd android && chmod +x ./gradlew
        # Build Command
    - name: Build Android Release
      run: yarn release
      # Upload to Artifact
    - name: Upload Artifact
      uses: actions/upload-artifact@v1
      with:
        name: app-release.apk
        path: android/app/build/outputs/apk/release/
